[env]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_microros_distro = jazzy
board_microros_transport = serial 
lib_deps =
    https://github.com/micro-ROS/micro_ros_platformio

[env:test_pub]
build_src_filter = +<${PIOENV}/*>

[env:entrainement]
build_src_filter = +<${PIOENV}/*>
lib_deps = 
    ${env.lib_deps}
    gin66/FastAccelStepper
    https://github.com/pololu/high-power-stepper-driver-arduino
    https://github.com/madhephaestus/ESP32Encoder

[env:driver]
build_src_filter = +<${PIOENV}/*>
lib_deps = 
    ${env.lib_deps}
    gin66/FastAccelStepper
    https://github.com/pololu/high-power-stepper-driver-arduino

[env:deadwheels]
build_src_filter = +<${PIOENV}/*>
lib_deps = 
    ${env.lib_deps}
    https://github.com/madhephaestus/ESP32Encoder

[env:manipulation]
build_src_filter = +<${PIOENV}/*>
