[env]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_microros_distro = humble
board_microros_transport = serial 
lib_deps =
    https://github.com/micro-ROS/micro_ros_platformio
    https://github.com/madhephaestus/ESP32Encoder

[env:encoder]
build_src_filter = +<${PIOENV}/*>

[env:test_pub]
build_src_filter = +<${PIOENV}/*>

[env:driver]
build_src_filter = +<${PIOENV}/*>

[env:deadwheels]
build_src_filter = +<${PIOENV}/*>